require:
  - rubocop-performance
  # - rubocop-rspec
  - rubocop-rails

AllCops:
  TargetRubyVersion: 3.0
  NewCops: enable
  Exclude:
    - vendor/**/*
    - db/**/*
    - bin/**/*
    - vendor/**/*
    - tmp/**/*
    - spec

Layout/LineLength:
  Max: 100

Metrics/ClassLength:
  Max: 150

Metrics/MethodLength:
  Max: 20

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Rails/HasAndBelongsToMany:
  Enabled: false

# Explicitness is better than implicitness
Style/RedundantArgument:
  Enabled: false

Naming/InclusiveLanguage:
  Enabled: false
