default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= Figaro.env.POSTGRES_USERNAME %>
  password: <%= Figaro.env.POSTGRES_PASSWORD %>
  host: <%= Figaro.env.POSTGRES_HOST %>
  port: <%= Figaro.env.POSTGRES_PORT %>

development:
  <<: *default
  database: <%= Figaro.env.POSTGRES_DATABASE %>

test:
  <<: *default
  database: <%= Figaro.env.POSTGRES_DATABASE %>
