default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: ShowYour1D!
  host: localhost
  port: 5432


development:
  <<: *default
  database: postgres_development
  username: postgres
  password: ShowYour1D!


test:
  <<: *default
  database: postgres_test
  username: postgres
  password: ShowYour1D!

